[tox]
envlist = py312,lint,type
isolated_build = true
skip_missing_interpreters = true

[testenv]
deps = .[test]
commands = pytest -q

[testenv:lint]
deps = ruff>=0.6.3
commands = ruff check .

[testenv:type]
deps = mypy>=1.11.2
commands = mypy app domain connectors mapping analytics